### ISSUE TITLE
Make Event page SEO friendly

### ISSUE THREAD

**Issue by trymebytes** [WordPress/wporg-gp-translation-events#218] opened 2024-04-17 12:10 UTC
Such that when events are shared on social media, the previews are displayed properly in Slack too.

**Comment by akirk** [comment] 2024-09-20 08:19
Likely this is caused by robots.txt blocking see [#356](https://github.com/WordPress/wporg-gp-translation-events/issues/356). Thus I'll close this in favor of the more specific issue.

**Closed as completed by akirk** 2024-09-20 08:19 UTC
